name: BuildTestClientApp

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
        working-directory: src/WebUI/ClientApp/
      - name: Run Tests
        run: npm run test:ci
        working-directory: src/WebUI/ClientApp/
