name: BuildTestServer

on:
  push:
    branches: [Deleting-offer-]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build and run Server
        run: dotnet run
        working-directory: src/WebUI/
      - name: UnitTests
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Application.UnitTests/
      - name: IntegrationTests
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Application.IntegrationTests/
