name: BuildTestServer

on:
  push:
    branches: [Deleting-offer-]

env:
  registry: my_registry_name
  # Not sure these are actually being passed down to rails, set them as the default in database.yml
  DB_HOST: localhost
  DB_USERNAME: test_user
  DB_PASSWORD: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build and run Server
        run: dotnet run
        working-directory: src/WebUI/
      - name: UnitTests
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Application.UnitTests/
      - name: IntegrationTests
        run: dotnet test --no-build --verbosity normal
        working-directory: tests/Application.IntegrationTests/
